# Generated by Django 5.2.4 on 2025-07-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='storage_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
