# Generated by Django 5.2.4 on 2025-07-23 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file_storage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
