# Generated by Django 5.2.4 on 2025-07-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_date_of_birth_user_first_name_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sources',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
