# Generated by Django 5.2.4 on 2025-07-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_preferred_llm_to_user'),
        ('core', '0005_message_sources'),
    ]

    operations = [
    ]
